version: '3.10'

services:
  db:
    image: postgres:15.1-alpine
    container_name: first_app_db
    environment:
      - POSTGRES_DB=first_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - .db:/var/lib/postgresql/data

volumes:
  db:
    driver: local