version: '3.10'

services:
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=first_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - .db:/var/lib/postgresql/data

volumes:
  db:
    driver: local