"""change orderings type

Revision ID: 7ebbf5d8b55b
Revises: 9da8e34c97a7
Create Date: 2023-02-11 15:15:25.032453

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7ebbf5d8b55b"
down_revision = "9da8e34c97a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lists",
        "ordering",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "tasks",
        "ordering",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "ordering",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "lists",
        "ordering",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
