"""renaming password to hashed_password

Revision ID: ddcc428b73e2
Revises: 5d8bd3ea97ae
Create Date: 2023-01-13 00:29:46.879733

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = 'ddcc428b73e2'
down_revision = '5d8bd3ea97ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password', nullable=False, new_column_name='hashed_password')
    # op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', nullable=False, new_column_name='password')
    # op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
