"""add is_deleted and is_activated column for models

Revision ID: e5fc1d70a028
Revises: ddcc428b73e2
Create Date: 2023-01-26 16:18:25.046943

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e5fc1d70a028"
down_revision = "ddcc428b73e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "boards",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=True),
    )
    op.add_column(
        "lists",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=True),
    )
    op.add_column(
        "tasks",
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("is_activated", sa.Boolean(), server_default="false", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_activated")
    op.drop_column("tasks", "is_deleted")
    op.drop_column("lists", "is_deleted")
    op.drop_column("boards", "is_deleted")
    # ### end Alembic commands ###
