"""add column description for lists

Revision ID: ebc18e63f69b
Revises: 5656a08c93bd
Create Date: 2023-02-24 16:51:26.771479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebc18e63f69b'
down_revision = '5656a08c93bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('description', sa.String(), nullable=True))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('lists', 'description')
    # ### end Alembic commands ###
