"""second

Revision ID: f2e3e4594f37
Revises: 8761871f8bd6
Create Date: 2022-11-24 21:47:07.216431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e3e4594f37'
down_revision = '8761871f8bd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'boards', ['id'])
    op.create_unique_constraint(None, 'lists', ['id'])
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_constraint(None, 'lists', type_='unique')
    op.drop_constraint(None, 'boards', type_='unique')
    # ### end Alembic commands ###
